MusicAlbum/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/' ,include('music.urls')),
    url(r'' , include('music.urls')),
]

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^index/$' ,views.index , name='index' ),
    url(r'^create_album/$' , views.create_album , name='create_album'),
    url(r'' , views.index , name='index'),
]

music/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class AlbumList(models.Model):
    #user = models.ForeignKey(User, default=1)
    album_title = models.CharField(max_length=500)
    artist = models.CharField(max_length=200)
    desc = models.CharField(max_length=1000)
    album_logo = models.FileField(max_length=2000)
    is_public = models.BooleanField(default=0)
    likes = models.IntegerField(default=None)
    def __str__(self):
        return self.album_title + '-' + self.artist

class SongList(models.Model):
    album = models.ForeignKey(AlbumList , on_delete=models.CASCADE)
    song_title = models.CharField(max_length=200)
    song_file = models.FileField(max_length=1000)
    is_public = models.BooleanField(default=False)
    likes = models.IntegerField(default=0)
    def __str__(self):
        return self.song_title

music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import AlbumList


class AlbumListForm(forms.ModelForm):

    class Meta:
        model = AlbumList
        fields = ['artist', 'album_title', 'desc', 'album_logo']

music/views.py
from django.shortcuts import render

# Create your views here.
from music.forms import AlbumListForm
from music.models import AlbumList

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

def index(request):
    albums = AlbumList.objects.all()
    return render(request , 'music/index.html' ,{'albums': albums})


def create_album(request):

    form = AlbumListForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        albums = form.save(commit=False)
        albums.user = request.user
        albums.album_logo = request.FILES['album_logo']
        file_type = albums.album_logo.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in IMAGE_FILE_TYPES:
            context = {
                'albums': albums,
                'form': form,
                'error_message': 'Image file must be PNG, JPG, or JPEG',
            }
            return render(request, 'music/create_album.html', context)
        albums.save()
        return render(request, 'music/detail.html', {'albums': albums})
    context = {
        "form": form,
    }
    return render(request, 'music/create_album.html', context)

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MusicAlbum{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="images/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}"></a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                 <li>
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Profile
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:create_album' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/create_album.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Viberr?</h3>
                    <p>Viberr is an app that allows you to upload and store all of your music on the cloud.</p>
                    <h3>How do I add music?</h3>
                    <p>First, create a new album by filling out the form on this page. Once an album is created you will be able to add/upload songs.</p>
                    <h3>What are some Album logo best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}


{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">

        </div>
        {% if albums %}
            {% for album in albums %}
                {% if album.is_public == True %}


                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                    {% if album.album_logo %}


                        <a href="{% url 'music:index' %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        {% else %}
                        <h2>No images for displaying</h2>
                         {% endif %}
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:index' %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:index' %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="{% url 'music:index' %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_public %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                {% endif %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:index' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}